// Code generated by protoc-gen-go.
// source: application/model/grpc_inputter.proto
// DO NOT EDIT!

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	application/model/grpc_inputter.proto

It has these top-level messages:
	Empty
	Request
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Some generic request with a message
type Request struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "model.Empty")
	proto.RegisterType((*Request)(nil), "model.Request")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GrpcInputterService service

type GrpcInputterServiceClient interface {
	// Accepts a message but doesn't return anything back
	MakeRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
}

type grpcInputterServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcInputterServiceClient(cc *grpc.ClientConn) GrpcInputterServiceClient {
	return &grpcInputterServiceClient{cc}
}

func (c *grpcInputterServiceClient) MakeRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/model.GrpcInputterService/MakeRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GrpcInputterService service

type GrpcInputterServiceServer interface {
	// Accepts a message but doesn't return anything back
	MakeRequest(context.Context, *Request) (*Empty, error)
}

func RegisterGrpcInputterServiceServer(s *grpc.Server, srv GrpcInputterServiceServer) {
	s.RegisterService(&_GrpcInputterService_serviceDesc, srv)
}

func _GrpcInputterService_MakeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcInputterServiceServer).MakeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.GrpcInputterService/MakeRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcInputterServiceServer).MakeRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcInputterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.GrpcInputterService",
	HandlerType: (*GrpcInputterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeRequest",
			Handler:    _GrpcInputterService_MakeRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/model/grpc_inputter.proto",
}

func init() { proto.RegisterFile("application/model/grpc_inputter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0x2c, 0x28, 0xc8,
	0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x4f, 0x2f,
	0x2a, 0x48, 0x8e, 0xcf, 0xcc, 0x2b, 0x28, 0x2d, 0x29, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x05, 0x4b, 0x29, 0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94, 0x54, 0x2a, 0x29,
	0x73, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16,
	0x17, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x46, 0x2e, 0x5c,
	0xc2, 0xee, 0x45, 0x05, 0xc9, 0x9e, 0x50, 0xa3, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85,
	0x74, 0xb9, 0xb8, 0x7d, 0x13, 0xb3, 0x53, 0x61, 0xfa, 0xf9, 0xf4, 0xc0, 0x66, 0xeb, 0x41, 0xf9,
	0x52, 0x3c, 0x50, 0x3e, 0xc4, 0x22, 0x86, 0x24, 0x36, 0xb0, 0x0b, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x8e, 0xde, 0x0f, 0x8b, 0xaa, 0x00, 0x00, 0x00,
}
